- name: launching instance using lightsail
  hosts: localhost
  connection: local
  tasks:
    - name: create a new lightsail instance & register the instance details
      lightsail:
        state: present
        name: myinstance
        region: us-east-1
        zone: us-east-1a
        blueprint_id: ubuntu_16_04
        bundle_id: nano_1_0
        key_pair_name: id_rsa
        user_data: "echo 'ubuntu lighsail instance' > /home/test.txt"
        wait_timeout: 500
        changed: true
      register: my_instance

    - debug:
        msg: " NAME is {{ my_instance.instance.name }}"

    - debug:
        msg: " IP is {{ my_instance.instance.public_ip_address }}"
